title: Strategic Technology
email: eric@strategictech.io
description: >- 
  A blog about technology.
  
  Virtualization, Containterization, Microservices, PowerShell, Python-- Software-Defined Everything.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.strategictech.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ephenix
linkedin_username: emphenix

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
